### PR TITLE
Add support for using a namespace other than App/Playbooks

### PR DESCRIPTION
**Pull request by fourstacks**
Hi @Skullbock 

Thanks for turning this into a package - was about to do the same this morning until I found yours!

This PR add support for both creating a new playbook in a directory other than `App\Playbooks` and also adds a config option to allow the developer to specify which custom directory the playbooks are in so that the `run` command works.

I've added tests and ensured that those without the new config option do not run into errors so it should be free of breaking changes.

### CODE REVIEW

**Comment by Skullbock** [comment]
Whoa, that's a super cool addition, thanks!

**Comment by Skullbock** [comment]
Let's see if Brent likes it.... :)

**Comment by fourstacks** [comment]
No worries - thanks for the quick merge!  If I have time I'll try and backfill some tests at some stage too - imagine I'll be using this a fair bit over a couple of projects

**Comment by Skullbock** [comment]
yeah, i was going to do that too.
Unfortunately i moved this into a package AFTER i finished the project for which i used the playbooks so... :)

Btw, i tagged 2.1.0 with your changes

Thanks again!

**Pull request merged**
